# ruff.toml
# Exclude third-party and upstream modules from checking
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "venv",
    ".venv",
    "modules",
    "imkit",
]

line-length = 120
indent-width = 4
