MiB = 1024 * 1024

TOTAL_RENDER_CACHE_BUDGET = 192 * MiB
TEXT_LAYER_TILE_BUDGET = 96 * MiB
CANONICAL_LAYOUT_BUDGET = 40 * MiB
QT_WORKER_PRIVATE_BUDGET = 40 * MiB
BODY_MASK_BUDGET = 16 * MiB

assert (
    TEXT_LAYER_TILE_BUDGET
    + CANONICAL_LAYOUT_BUDGET
    + QT_WORKER_PRIVATE_BUDGET
    + BODY_MASK_BUDGET
    <= TOTAL_RENDER_CACHE_BUDGET
)
