"""Shared user-facing defaults and UI constants."""

OLLAMA_REQUEST_TIMEOUT_SECONDS = 90
OLLAMA_CONNECTION_TIMEOUT_SECONDS = 5.0
DEFAULT_OPENAI_COMPATIBLE_API_BASE_URL = "http://127.0.0.1:8080/v1"
OFFLINE_MODEL_DISPLAY_NAME = "Ollama 오프라인 (기본 모델)"
STATUS_AUTO_HIDE_MS = 1000
MODEL_COMBO_MIN_WIDTH = 320
